version: "3"
services:
  spacenet-notebooks:
    build:
      context: notebooks
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./notebooks:/home/work
      - ./data:/home/data