name: spacenet
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab
  - python=3.9
  - matplotlib
  - pandas
  - earthpy
  - pytorch
  - torchvision
  - scikit-learn
  - scikit-image
  - descartes
  - tqdm
  - imgaug
  - albumentations
  - ipywidgets
